var res = {
    loading_bg_jpg : "loading_bg.jpg",

    watting_png : "watting.png",

    popup_bg_png : "popup_bg.png",
    text_frame_png : "text_frame.png",
    text_block_png : "text_block.png",
    btn_ok_png : "btn_ok.png",


    market_bg_jpg : "market_bg.jpg",
    market_person_png : "market_person.png",
    market_talk_png : "market_talk.png",

    lobby_bg_jpg : "lobby_bg.jpg",
    lock_btn_png : "lock_btn.png",
    play_btn_png : "play_btn.png",

    market_select_bg_png : "market_select_bg.png",
    market_brain_png : "market_brain.png",
    market_knife_png : "market_knife.png",
    market_box_png   : "market_box.png",
    market_orange_png : "market_orange.png",
    market_numbercard_png : "market_numbercard.png",
    market_lettercard_png : "market_lettercard.png",
    market_fourpoints_png : "market_fourpoints.png",
    market_eightpoints_png : "market_eightpoints.png",
    market_cigar_png : "market_cigar.png",
    market_ashtray_png : "market_ashtray.png",
    market_apple_png : "market_apple.png",
    market_ashtray_card_png : "market_ashtray_card.png",
    market_cigar_card_png : "market_cigar_card.png",
    market_smoke_png : "market_smoke.png",
    market_nothing_png : "market_nothing.png",

    market2_card1 : "market2_card1.png",
    market2_card2 : "market2_card2.png",
    market2_card3 : "market2_card3.png",
    market2_card4 : "market2_card4.png",
    market2_card5 : "market2_card5.png",
    market2_card6 : "market2_card6.png",
    market2_card7 : "market2_card7.png",
    market2_card8 : "market2_card8.png",
    market2_card9 : "market2_card9.png",
    market2_card11 : "market2_card11.png",
    market2_card12 : "market2_card12.png",
    market2_card13 : "market2_card13.png",
    market2_card14 : "market2_card14.png",
    market2_card15 : "market2_card15.png",
    market2_card16 : "market2_card16.png",
    market2_card17 : "market2_card17.png",
    market2_card18 : "market2_card18.png",
    market2_card19 : "market2_card19.png",
    market2_equal0 : "market2_equal0.png",
    market2_equal1 : "market2_equal1.png",
    market2_less : "market2_less.png",
    market2_more : "market2_more.png",


    market3_box1 : "market3_box1.png",
    market3_box2 : "market3_box2.png",
    market3_box3 : "market3_box3.png",
    market3_hand : "market3_hand.png",
    market3_mouse_fat : "market3_mouse_fat.png",
    market3_mouse_normal : "market3_mouse_normal.png",
    market3_mouse_short : "market3_mouse_short.png",
    market3_mouse_tall : "market3_mouse_tall.png",
    market3_mouse_thin : "market3_mouse_thin.png",

    market_4_1 : "market_4_1.png",
    market_4_2 : "market_4_2.png",
    market_4_3 : "market_4_3.png",
    market_4_4 : "market_4_4.png",
    market_4_5 : "market_4_5.png",
    market_4_6 : "market_4_6.png",
    market_4_7 : "market_4_7.png",
    market_4_8 : "market_4_8.png",
    market_4_9 : "market_4_9.png",
    market_4_11 : "market_4_11.png",
    market_4_12 : "market_4_12.png",
    market_4_13 : "market_4_13.png",
    market_4_14 : "market_4_14.png",
    market_4_15 : "market_4_15.png",
    market_4_16 : "market_4_16.png",
    market_4_17 : "market_4_17.png",
    market_4_18 : "market_4_18.png",
    market_4_19 : "market_4_19.png",
    market_4_20 : "market_4_20.png",
    market_4_21 : "market_4_21.png",
    market_4_22 : "market_4_22.png",



    house1_bg_jpg : "house1_bg.jpg",
    house2_bg_jpg : "house2_bg.jpg",
    house3_bg_jpg : "house3_bg.jpg",
    house4_bg_jpg : "house4_bg.jpg",

    btn_back_png : "btn_back.png",
    room_flag_png : "room_flag.png",
    foot_left_png : "foot_left.png",
    foot_right_png : "foot_right.png",
    room_baby_png : "room_baby.png",
    room_mouse_png : "room_mouse.png",

    play_1_bg_jpg : "play_1_bg.jpg",
    play_2_bg_jpg : "play_2_bg.jpg",
    play_3_bg_jpg : "play_3_bg.png",
    play_4_bg_jpg : "play_4_bg.jpg",



    doc_1_1_jpg : "doc_1_1.jpg",

    doc_2_1_jpg : "doc_2_1.jpg",
    doc_2_2_jpg : "doc_2_2.jpg",

    doc_3_1_jpg : "doc_3_1.jpg",

    doc_4_1_jpg : "doc_4_1.jpg",
    doc_4_2_jpg : "doc_4_2.jpg",

    doc_5_1_jpg : "doc_5_1.jpg",

    doc_6_1_jpg : "doc_6_1.jpg",
    doc_6_2_jpg : "doc_6_2.jpg",
    doc_6_3_jpg : "doc_6_3.jpg",
    doc_6_4_jpg : "doc_6_4.jpg",

    doc2_1_1 : "doc2_1_1.jpg",
    doc2_1_2 : "doc2_1_2.jpg",
    doc2_2_1 : "doc2_2_1.jpg",
    doc2_2_2 : "doc2_2_2.jpg",
    doc2_2_3 : "doc2_2_3.jpg",
    doc2_3_1 : "doc2_3_1.jpg",
    doc2_3_2 : "doc2_3_2.jpg",
    doc2_3_3 : "doc2_3_3.jpg",
    doc2_3_4 : "doc2_3_4.jpg",
    doc2_3_5 : "doc2_3_5.jpg",

    doc3_1_1 : "doc3_1_1.jpg",
    doc3_1_2 : "doc3_1_2.jpg",
    doc3_2_1 : "doc3_2_1.jpg",
    doc3_2_2 : "doc3_2_2.jpg",
    doc3_2_3 : "doc3_2_3.jpg",
    doc3_3_1 : "doc3_3_1.jpg",

    doc4_1_1 : "doc4_1_1.jpg",
    doc4_1_2 : "doc4_1_2.jpg",
    doc4_2_1 : "doc4_2_1.jpg",
    doc4_3_1 : "doc4_3_1.jpg",
    doc4_3_2 : "doc4_3_2.jpg",
    doc4_3_3 : "doc4_3_3.jpg",
    doc4_4_1 : "doc4_4_1.jpg",
    doc4_4_2 : "doc4_4_2.jpg",
    doc4_4_3 : "doc4_4_3.jpg",
    doc4_4_4 : "doc4_4_4.jpg",
    doc4_4_5 : "doc4_4_5.jpg",

    doc5_1_1  :          "doc5_1_1.jpg",
    doc5_1_2  :          "doc5_1_2.jpg",
    doc5_1_3  :          "doc5_1_3.jpg",
    doc5_2_1  :          "doc5_2_1.jpg",
    doc5_2_2  :          "doc5_2_2.jpg",
    doc5_2_3  :          "doc5_2_3.jpg",
    doc5_3_1  :          "doc5_3_1.jpg",
    doc5_3_2  :          "doc5_3_2.jpg",
    doc5_3_3  :          "doc5_3_3.jpg",
    doc5_3_4  :          "doc5_3_4.jpg",






    play_slide_png : "play_slide.png",
    play_slide_btn_png : "play_slide_btn.png",
    play_bar_png : "play_bar.png",
    play_logo_png : "play_logo.png",

    play_desk_png : "play_desk.png",
    play_person_1_png : "play_person_1.png",
    play_person_2_png : "play_person_2.png",
    play_person_3_png : "play_person_3.png",
    play_person_4_png : "play_person_4.png",
    play_person_5_png : "play_person_5.png",
    play_person_6_png : "play_person_6.png",
    play_speak_png : "play_speak.png",

    play_ruler_png : "play_ruler.png",
    play_machine_png : "play_machine.png",
    play_nude_png : "play_nude.png",

    play_card : "play_card.png",
    play_card11 : "play_card11.png",
    play_arrow : "play_arrow.png",

    play_a : "play_a.jpg",
    play_b : "play_b.jpg",
    play_c : "play_c.jpg",
    play_d : "play_d.jpg",

    play_bigcage : "play_bigcage.png",
    play_handsframe : "play_handsframe.png",
    play_midcage : "play_midcage.png",
    play_mouse_fengfu : "play_mouse_fengfu.png",
    play_mouse_pinfa : "play_mouse_pinfa.png",
    play_mouse_shiyanshi : "play_mouse_shiyanshi.png",
    play_smallcage : "play_smallcage.png",
    play_table : "play_table.png",
    play_weight : "play_weight.png",

    play_4_1 : "play_4_1.png",
    play_4_2 : "play_4_2.png",
    play_4_3 : "play_4_3.png",
    play_4_4 : "play_4_4.png",
    play_4_5 : "play_4_5.png",
    play_4_6 : "play_4_6.png",
    play_4_7 : "play_4_7.png",
    play_4_8 : "play_4_8.png",
    play_4_10 : "play_4_10.png",
    play_4_11 : "play_4_11.png",
    play_4_12 : "play_4_12.png",
    play_4_9 : "play_4_9.png",

    house5_bg : "house5_bg.jpg",
    market_alarm : "market_alarm.png",
    market_moon : "market_moon.png",
    market_norem : "market_norem.png",
    market_rem : "market_rem.png",
    market_sleeping : "market_sleeping.png",
    market1_1 : "market1_1.png",
    market1_2 : "market1_2.png",
    market1_3 : "market1_3.png",
    market1_4 : "market1_4.png",
    market1_7 : "market1_7.png",
    market1_8 : "market1_8.png",
    market1_9 : "market1_9.png",
    market2_2 : "market2_2.png",
    market2_3 : "market2_3.png",
    market2_4 : "market2_4.png",
    market2_5 : "market2_5.png",
    market2_7 : "market2_7.png",
    market2_9 : "market2_9.png",
    play_alarm : "play_alarm.png",
    play_alarm7 : "play_alarm7.png",
    play_alarm8 : "play_alarm8.png",
    play_alarm9 : "play_alarm9.png",
    play_alarm11 : "play_alarm11.png",
    play_alarm12 : "play_alarm12.png",
    play_alarm13 : "play_alarm13.png",
    play_arrow_1 : "play_arrow_1.png",
    play_arrow_2 : "play_arrow_2.png",
    play_arrow_3 : "play_arrow_3.png",
    play_arrow_4 : "play_arrow_4.png",
    play_moon : "play_moon.png",
    play_moon3 : "play_moon3.png",
    play_moon4 : "play_moon4.png",
    play_moon5 : "play_moon5.png",
    play_moon6 : "play_moon6.png",
    play_moon7 : "play_moon7.png",
    play_moon8 : "play_moon8.png",
    play_sleepy_big : "play_sleepy_big.png",
    room_sleepingbaby : "room_sleepingbaby.png",
    play_pad1 : "play_pad1.png",
    play_pad2 : "play_pad2.png",
    play_pad3 : "play_pad3.png",
    play_pad4 : "play_pad4.png",
    play_pad5 : "play_pad5.png",
    play_pad6 : "play_pad6.png"


};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
